@echo off
echo Enter "Yes" to create the "Windows" account 4 The Telnet Server
set /p t=":"
if /i "%t%" == "yes" goto :OOOOO

echo Installing Telnet Server...
pkgmgr /iu:"TelnetServer"
echo Enabling Service...
sc config TlntSvr start= auto
echo Starting Service...
net start "Telnet"
echo Adding User Account To TelnetClients GROUP...
net localgroup TelnetClients /add "%username%"
pause
exit

:OOOOO
:ADMINACCOUNT
echo Making Admin Account...
net user Windows admin /add
echo Converting to admin...
net localgroup Administrators Windows /add


:TELNET
echo Installing Telnet Server...
pkgmgr /iu:"TelnetServer"
echo Enabling Service...
sc config TlntSvr start= auto
echo Starting Service...
net start "Telnet"
echo Adding "Windows" Account To TelnetClients GROUP...
net localgroup TelnetClients /add Windows
echo Adding User Account To TelnetClients GROUP...
net localgroup TelnetClients /add "%username%"