@echo off
:: SD-Security (C) Loading Screen
:: All Rights Reserved
::
:: This
:: SD-Security Is Open Source, Meaning So Is This Loading Indicator
:: To Use This API Insert This Code, Replace 'f0' (second line) With The Colour You Want The Screen To Have(Replace The First And Last Line With Your Own Script):
::
::    echo loading
::    set color=f0
::    if exist "SDSLoad.tmp" attrib -h "SDSLoad.tmp"&del SDSLoad.tmp
::    call start loading.exe %color%
::    :SDloading
::    if not exist "SDSLoad.tmp" goto SDloading
::    attrib -h "SDSLoad.tmp"&del SDSLoad.tmp
::    echo finished loading
::
:beginning
color %1
cls
mode con: cols=28 lines=5
set loadnum=0
:LOADING
set/a loadnuminhundred=%loadnuminhundred% +4
cls
title Loading %loadnuminhundred%%%
if %loadnum%==24 set load=%load%Û&goto lastLoadingStep
set load=%load%þ
:lastLoadingStep
echo.
echo  ÛßßßßßßßßßßßßßßßßßßßßßßßßÛ
echo  Û%load%
echo  ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
ping localhost -n 1 >nul
ping localhost -n 1 >nul
set/a loadnum=%loadnum% +1
set/a loadnumber=%loadnumber% +3
if %loadnum%==25 goto finished
goto LOADING
:finished
echo You Can Safely Delete This File, File Was Generated By A SD-Security API> "SDSLoad.tmp"
attrib +h "SDSLoad.tmp"
exit